
#
# Build Workflow
#

name: Build

run-name: ${{ github.actor }} started a build.

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create build system
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
      - name: Build Project
        run: cmake --build build --config Release

  Windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create build system
        run: cmake -S . -B build -G"Visual Studio 17 2022" -DCMAKE_BUILD_TYPE=Release
      - name: Build Project
        run: cmake --build build --config Release